# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KXUevzqbVZGsS2QrO6fPjgwKFLHiUD9J
"""

#question number 1 from in class excercise 11
datafile = open("WorldSeriesWinners.txt",'r')
#open file
teamlist=[]
for line in datafile:
  teamlist.append(line.rstrip())
datafile.close()

#input
teamname = input("Enter the name of the team ")

#counting how many time a team won
count=0
year=1903
for team in teamlist:
  if team.lower() == teamname.lower():
    if year>=1904: year = year+1
    if year>1994: year=year+1
    print(year)
    count = count+1
  year=year+1
print(teamname,"has won",count,"times of world series!")

#importing matplotlib
import matplotlib.pyplot as plt
#reading data from file
datafile = open("USPopulation.txt","r")

populationdata=[]
for line in datafile:
  populationdata.append(int(line.rstrip()))

xcor = list(range(41))
ycor = populationdata
plt.plot(xcor,ycor)

plt.title("US Population") # This line is now correct
plt.xlabel("Years")
plt.ylabel("Population in Thousands")

plt.xticks(list(range(0,41,5)),list(range(1950,1991,5)))
plt.show()