# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VSp6qZcoficgK5ZI3RPDUhwz6YYP6sEF
"""

#programming assignment 11 question 1
#importing matplotlib
import matplotlib.pyplot as plt


#programming assignment 11 question 1
datafile = open("expenses.txt","r")
expenses=[]
for line in datafile:
  expenses.append(line.rstrip())
datafile.close()

slice_labels = ["Rent","Gas","Food","Clothing","Car Payment","Msc"]
plt.pie(expenses,labels=slice_labels)
plt.show()

#programming assignment 1question 2
#importing matplotlib
import matplotlib.pyplot as plt

#opening document
datafile = open("Weekly_Gas_Averages.txt","r")
gas_price = []
for line in datafile:
  gas_price.append(line.rstrip())
datafile.close()

#plotting
xcor = list(range(1,53))
ycor = gas_price
plt.plot(xcor,ycor)
plt.title("1994 Weekly Gas Price")
plt.xlabel("Weeks(by number)")
plt.ylabel("Average Prices")
plt.xticks(list(range(0,53,10)))
plt.show()

